# Generated by Django 2.1.3 on 2018-11-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.TextField()),
                ('Modelo', models.TextField()),
                ('Anio', models.TextField()),
                ('Color', models.TextField()),
                ('NroPuertas', models.TextField()),
                ('Descripcion', models.TextField()),
                ('FechaPublicacion', models.TextField()),
                ('Precio', models.TextField()),
            ],
        ),
    ]
