# Generated by Django 2.1.3 on 2018-11-09 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovil',
            name='FechaPublicacion',
        ),
        migrations.AddField(
            model_name='automovil',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='automovil',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
